### ISSUE TITLE
Building on Rasbian

### ISSUE THREAD

**Issue by adigeo** [SiriDB/siridb-server#101]
I am not able to build it on:

Name: Raspbian GNU/Linux 8 (jessie)
Version: 8 (jessie)
Codename: jessie

pi@attic92:~/work/siridb-server/Release $ make
Building file: ../src/xpath/xpath.c
Invoking: GCC C Compiler
gcc -I../include -O3 -Wall -Wextra   -c -fmessage-length=0 -MMD -MP -MF"src/xpath/xpath.d" -MT"src/xpath/xpath.o" -o "src/xpath/xpath.o" "../src/xpath/xpath.c"
Finished building: ../src/xpath/xpath.c
 
Building file: ../src/xmath/xmath.c
Invoking: GCC C Compiler
gcc -I../include -O3 -Wall -Wextra   -c -fmessage-length=0 -MMD -MP -MF"src/xmath/xmath.d" -MT"src/xmath/xmath.o" -o "src/xmath/xmath.o" "../src/xmath/xmath.c"
Finished building: ../src/xmath/xmath.c
 
Building file: ../src/timeit/timeit.c
Invoking: GCC C Compiler
gcc -I../include -O3 -Wall -Wextra   -c -fmessage-length=0 -MMD -MP -MF"src/timeit/timeit.d" -MT"src/timeit/timeit.o" -o "src/timeit/timeit.o" "../src/timeit/timeit.c"
Finished building: ../src/timeit/timeit.c
 
Building file: ../src/test/test.c
Invoking: GCC C Compiler
gcc -I../include -O3 -Wall -Wextra   -c -fmessage-length=0 -MMD -MP -MF"src/test/test.d" -MT"src/test/test.o" -o "src/test/test.o" "../src/test/test.c"
../src/test/test.c: In function ‘test_gen_pool_lookup’:
../src/test/test.c:475:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < 30; i++)
     ^
../src/test/test.c:475:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
../src/test/test.c: In function ‘test_points’:
../src/test/test.c:492:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < 5; i++)
     ^
../src/test/test.c:498:17: error: conflicting types for ‘i’
     for (size_t i = 0; i < points->len; i++)
                 ^
../src/test/test.c:492:14: note: previous definition of ‘i’ was here
     for (int i = 0; i < 5; i++)
              ^
../src/test/test.c:498:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (size_t i = 0; i < points->len; i++)
     ^
src/test/subdir.mk:18: recipe for target 'src/test/test.o' failed
make: *** [src/test/test.o] Error 1

**Comment by adigeo** [comment]
Worked with export CFLAGS="-std=gnu99"

**Comment by joente** [comment]
SiriDB Server can now also compile with `gnu89`/`gnu90`. `POSIX` is still required since the code is using things like `fseeko` and `readlink` which are not available in `ISO C90`.
