### ISSUE TITLE
Use of parentheses in combination with update functions

### ISSUE THREAD

**Issue by AnjaBruls** [SiriDB/siridb-server#111]
When using update functions it is not possible yet to indicate precendence by using parentheses. 

This would be a good feature to add so that the following query example is possible:
```
list series /series.*/ - ('series_001' | 'series_005')
```
The intended result of this query is to collect all series that start their name with 'series' except  'series_001' and 'series_005'.

**Comment by joente** [comment]
Added `parenthesis` feature in `dev` branch. Additional tests are still required.

**Comment by joente** [comment]
Tests for using `parenthesis` are added.
