### ISSUE TITLE
number of databases is limited to 4

### ISSUE THREAD

**Issue by lilvinz** [SiriDB/siridb-server#114]
There is a hard limit of 4 databases for no apparent reason.

https://github.com/SiriDB/siridb-server/blob/master/include/siri/siri.h#L20

Either it should be documented with proper reasoning or removed completely.

**Comment by joente** [comment]
@lilvinz , there is indeed not a very good reason for the 4 limit, except that SiriDB uses a thread from the main thread pool for each database to update group information. However this limitation can be easy removed. I've updated the `dev` branch and changed the limit to 1024 for now. We are currently adding some tests to see if everything works as expected.

**Comment by joente** [comment]
merged with `master`
