### ISSUE TITLE
Installation on a RedHat machine

### ISSUE THREAD

**Issue by thebuleon29** [SiriDB/siridb-server#119]
Hi,
I followed all the instructions to compile the code on a linux machine. The make test runs without raising any error and the make command seems to run correctly as well. But after that, the siridb-server command is unknown and there is no /etc/siridb directory where to put my siridb.conf file. the docker integration test doesn't work either, saying ""ubuntu:18.04 as builder" is not a valid repository/tag: invalid reference format".

Am I doing some thing wrong ?

**Comment by joente** [comment]
After running `make`, siridb-server is compiled in either the `./Debug` or `./Release` path, depending on your choice. 

To simplify things, I've updated the master branch and included a basic `make install` and `make uninstall` which creates the required directories, and copies siridb-server to `/usr/bin` (see updated README.md)

As for the docker issue, I can build build the integration test just fine. I'm using docker version `18.03.1-ce` and `18.09.2`, what version are you using?

**Comment by thebuleon29** [comment]
You're right about the docker part, I was running an old version. My bad. 
Thanks a lot for the update, it's perfect now !
