### ISSUE TITLE
Inserting series in a loop causes fatal crash

### ISSUE THREAD

**Issue by Botje** [SiriDB/siridb-server#125]
I modified the Python example slightly to quickly insert a few large series:
```python
import asyncio
from datetime import datetime, timedelta
import random
import uuid
from siridb.connector import SiriDBClient

async def example(siri):
    await siri.connect()

    try:
        inc = timedelta(minutes=15)
        start = datetime(2020,1,1)
        end = datetime(2021,1,1) - inc
        quarters = int((end - start) / inc)
        for _ in range(100):
            values = [ (int((start + i * inc).timestamp()), random.random()) for i in range(quarters) ]

            await siri.insert({f'{str(uuid.uuid4())}': values})

    finally:
        # Close all SiriDB connections.
        siri.close()


siri = SiriDBClient(
    username='iris',
    password='siri',
    dbname='dbtest',
    hostlist=[('localhost', 9000)],  # Multiple connections are supported
    keepalive=True)

loop = asyncio.get_event_loop()
loop.run_until_complete(example(siri))
```

This causes a reproducible crash on version 687835d3b764406b2d2a933e308f0352c6ce2b8c on macOS 10.14.6:
[crashlog.txt](https://github.com/SiriDB/siridb-server/files/4254661/crashlog.txt)

If I restart the server and try again, occasionally I get a different crashlog:
[crashlog2.txt](https://github.com/SiriDB/siridb-server/files/4254673/crashlog2.txt)
All mentioned files exist, so I'm guessing this is some kind of race condition with the filesystem?

**Comment by joente** [comment]
@Botje , I've fixed the logging for when creating a new shard has failed. Could you try to pull and build SiriDB from the [issue125](https://github.com/SiriDB/siridb-server/tree/issue125 ) branch and try the script again?

btw. On my Linux laptop your python script runs fine, so I suspect it is indeed a problem with your file system. Maybe access permissions, or insufficient disk space?

**Comment by joente** [comment]
@Botje, I realized the implementation of `stderr_r` is different for `__GLIBC__` so I made a small change to be portable with mac os.

**Comment by Botje** [comment]
That helped me locate the issue: opening new shard files failed because macOS has a default maximum filedescriptor limit of 256. Perhaps the initialization should bail out if the limit could not be raised.

Thanks for the quick response!

**Comment by joente** [comment]
SiriDB reads the file descriptor limit at startup and should still work even with a lower maximum like 256. I found a bug at this point in the code, we first try to re-configure the limit, and only if that fails, the amount of file descriptors it may use should be adjusted. The problem was that we still configured a value which was too high..

The bug is fixed (in the issue125 branch), so SiriDB should now work fine even with the 256 limit.

**Comment by Botje** [comment]
With that change (36123fbfde87bd92fb427da4bac4ac3050152ac2) I cannot break it. Thanks again!
