### ISSUE TITLE
User authentication request failed: invalid credentials

### ISSUE THREAD

**Issue by mingfai** [SiriDB/siridb-server#127]
except siridb-admin, siridb-prompt (2.1.6), siridb-http(2.0.13), and the old java connector (latest from github) fail to authenticate. With siridb-admin 1.2.0, created a new database "abcd", tested credentials as the default sa/siri and also a new service account. The server debug log for sa/siri shows:
```
[D 2020-03-25 10:50:32] Received a TCP client connection request.
[D 2020-03-25 10:50:32] Package received from client 'IP_ADDRESS_REMOVED:61322' (pid: 0, len: 14, tp: CPROTO_REQ_AUTH)
[W 2020-03-25 10:50:32] User authentication request failed: invalid credentials
```

The initial boot up logs are as follows:
```
[I 2020-03-25 11:08:31] Starting SiriDB Server (version: 2.0.35)
[D 2020-03-25 11:08:31] Read 'server_name' from config: MY_HOST_NAME:9010
[W 2020-03-25 11:08:31] Missing 'http_status_port' in '/etc/siridb/siridb.conf' (option not found). Using default value: 0
[W 2020-03-25 11:08:31] Missing 'http_api_port' in '/etc/siridb/siridb.conf' (option not found). Using default value: 0
[I 2020-03-25 11:08:31] Increasing soft-limit from 1024 to 65535 since we want to use only 50% from the soft-limit for shard files
[W 2020-03-25 11:08:31] Missing 'enable_pipe_support' in '/etc/siridb/siridb.conf' (option not found). Disable pipe support
[W 2020-03-25 11:08:31] Missing 'buffer_sync_interval' in '/etc/siridb/siridb.conf' (option not found). Using default value: 0
[I 2020-03-25 11:08:31] Start listening for back-end connections on port 9010
[I 2020-03-25 11:08:31] Start listening for TCP client connections on port 9000
[I 2020-03-25 11:08:31] Database is successfully locked with a new lock file (/MY_DATABASE_PATH/abcd/)
[D 2020-03-25 11:08:31] Set number duration mask to 32
[D 2020-03-25 11:08:31] Set log duration mask to 12
[D 2020-03-25 11:08:31] No tee pipe name configured for database: abcd
[I 2020-03-25 11:08:31] Start loading database: 'abcd'
[I 2020-03-25 11:08:31] Loading users
[I 2020-03-25 11:08:31] Loading servers
[I 2020-03-25 11:08:31] Loading series
[D 2020-03-25 11:08:31] Loading dropped series
[D 2020-03-25 11:08:31] Cleanup series file
[I 2020-03-25 11:08:31] Loading shards
[I 2020-03-25 11:08:31] Loading and cleanup buffer
[I 2020-03-25 11:08:31] Loading groups
[I 2020-03-25 11:08:31] Updating series properties
[I 2020-03-25 11:08:31] Initialize pools
[I 2020-03-25 11:08:31] Finished loading database: 'abcd'
[D 2020-03-25 11:08:32] Start heart-beat task
[D 2020-03-25 11:09:02] Start heart-beat task
```
I do see the warning but they do not seem to be related to authentication.

The test was done on a Ubuntu 18.04.2(4.15.0-20-generic) I tried two versions, 2.0.26-1 (bionic,amd64 from apt) and 2.0.35 (manual build), results are the same. Tried to run the server with root and non-root account. The client port is listening properly.

I actually tried to troubeshoot at the code level to understand how the system work. The 14-byte QPack auth request message should be a String array of user:pass:dbname, and I added debug log to print the username and password on the server, and I see they are sent correct. (shown as "sa" and "siri") 

All siridb-admin commands are fine. I am able to list accounts and databases, create database etc. So the server should be running properly. 

so, any idea what goes wrong?

**Comment by joente** [comment]
SiriDB uses the `sa` service account (by default) for creating databases, pools and other service accounts. Each database has it's own users, the default user for a new database is `iris` with password `siri`. The password (or user) may later be changed with `alter user 'iris' set password 'xxxx'`

**Comment by mingfai** [comment]
thx. it works. 

only after your reply, I searched on github with "iris" and know at the siridb-admin page, it mentioned the default "iris" user account. however, I actually did the "new-database" without problem, so i never check that section of documentation. only when i run siridb-http and siridb-prompt i found the sa/siri password do not work. 

given that there are at least two other issues about not knowing the default account, i.e. #15 and #91, maybe you could consider to add such information in other place.

**Comment by joente** [comment]
@mingfai , you are right that it might be a bit confusing with the two accounts. Maybe it is also an option to at least write another waning message in the console in case a failed attempt is done using user `sa`. SiriDB could write a warning log like:

 _"User authentication request failed: invalid credentials for user `sa`, did you mean to use the default database user `iris`?"_ 

instead of the default message:

 _"User authentication request failed: invalid credentials"_

Usually you don't want to leak hints about user names in the log, but since both sa and iris are default I don't think this would cause trouble.
