### ISSUE TITLE
File corruption after unclean shutdown

### ISSUE THREAD

**Issue by ubnt-michals** [SiriDB/siridb-server#130]
We are getting what looks like file corruption after server hard reset.

SiriDB Log:
```
Expected end of file '/var/lib/siridb/xyz/series.dat'
Could not read series for database 'xyz'
Could not load 'xyz'.
```

Client log:
```
Connected to SiriDB server version: 2.0.34
SiriDB database 'xyz' does not exists. Creating...
SiriDbError: database directory already exists: /var/lib/siridb/xyz/
```

This is on customer server, we are waiting for the files. I assume `series.dat` is somehow corrupted. Any way to fix this?

EDIT: It's not an isolated incident, but I am currently unable to reproduce this.

**Comment by joente** [comment]
@ubnt-michals , did you try to start SiriDB using `v2.0.37-alpha-1`?

**Comment by ubnt-michals** [comment]
@joente We managed to boot SiriDB `v2.0.37-alpha-1` with broken `series.dat` and so far everything looks good. Thanks for prompt fix.
