### ISSUE TITLE
siridb-server error at startup

### ISSUE THREAD

**Issue by cbiale** [SiriDB/siridb-server#142]
siridb-server version: 2.0.38
Installer: siridb-server_2.0.38-0.tt1_amd64.deb

At the startup the program shows the following error:
**siridb-server: symbol lookup error: siridb-server: undefined symbol: cleri_parse**

**Comment by joente** [comment]
@cbiale, can you tell which version of libcleri is installed?

**Comment by joente** [comment]
@cbiale, can you try the file below? The current `deb` files attached to the release are created using Ubuntu 18.04 with `libcleri-0.9.4` but the attached debian file is created using Ubuntu 20.04 with `libcleri-0.11.0` which is probably compatible with the version you are using.

[siridb-server_2.0.39-0~tt1_amd64.deb.zip](https://github.com/SiriDB/siridb-server/files/5254798/siridb-server_2.0.39-0.tt1_amd64.deb.zip)

**Comment by cbiale** [comment]
> @cbiale, can you try the file below? The current `deb` files attached to the release are created using Ubuntu 18.04 with `libcleri-0.9.4` but the attached debian file is created using Ubuntu 20.04 with `libcleri-0.11.0` which is probably compatible with the version you are using.
> 
> [siridb-server_2.0.39-0~tt1_amd64.deb.zip](https://github.com/SiriDB/siridb-server/files/5254798/siridb-server_2.0.39-0.tt1_amd64.deb.zip)

@joente thank you!!!
Its working!!

**Comment by joente** [comment]
@cbiale , For SiriDB version 2.0.40 I have added the following deb file for Ubnutu 20.04: https://github.com/SiriDB/siridb-server/releases/download/2.0.40/siridb-server_2.0.40-0.focal-fossa1_amd64.deb
