### ISSUE TITLE
What is the best way to create a single server backup?

### ISSUE THREAD

**Issue by ubnt-michals** [SiriDB/siridb-server#143]
I was wondering what is the best way to create a server backup.

Preferably I don't want to stop the server and stop consuming new data (I know I could stop the server and copy the files). Having multiple servers as a backup is unfortunately not an option for our deployment. We need to make a cold storage backup.

I currently think about dumping series in batches (keeping data in qpack format) and in case we need to restore I would load the qpack to back an empty database.

But maybe there is a better option.

**Comment by joente** [comment]
@ubnt-michals , for the [backup_mode](https://docs.siridb.net/servers/alter_server/backup_mode/) you need a replica server to keep the database running. The backup_mode option is created so SiriDB does not require a shutdown and still closes all open files.

Maybe you can store SiriDB on a volume from which you can take hot snapshots?

**Comment by m1ch4ls** [comment]
We ended up dumping all series in batches. It turned out it would be complicated to set up a replica in our Docker setup.

@joente Feel free to close the issue.
