### ISSUE TITLE
Database cannot be loaded after power outage due to duplicate values in series.dat

### ISSUE THREAD

**Issue by prvak** [SiriDB/siridb-server#148]
Sometimes, probably after a power outage or an unclean server reboot, the siridb fails to load database without any specific error:
```
[I 2020-10-19 08:55:33] Loading series
[D 2020-10-19 08:55:33] Loading dropped series
[E 2020-10-19 08:55:33] Could not read series for database 'db'
[E 2020-10-19 08:55:33] Could not load 'db'.
```

The problem seems to be that `series.dat` file contains duplicate values
```
$ strings series.dat | sort
...
device.76d803c6-dc33-4a6a-894c-a94a6aa9c636.localChain1
device.76d803c6-dc33-4a6a-894c-a94a6aa9c636.ping <----
device.76d803c6-dc33-4a6a-894c-a94a6aa9c636.ping <----
device.76d803c6-dc33-4a6a-894c-a94a6aa9c636.ram
...
```

and `ct_add` returns value `CT_EXISTS (1)`
https://github.com/SiriDB/siridb-server/blob/179e8280a809b95c3138d4a76267d573262daead/src/siri/db/series.c#L1596-L1600

Here is an example of the corrupted file: [series.dat.zip](https://github.com/SiriDB/siridb-server/files/5402000/series.dat.zip)

Is there a way to fix it? Is it possible to somehow drop only the duplicate series and load the rest of the database?

**Comment by joente** [comment]
@prvak , I can only imagine this happens if the dropped series file is not correctly written to disk. Therefore I think the best option is to keep the series with the highest ID(s). I've updated the `master` branch to version 2.0.41-alpha-1 which logs an error and then continues when a duplicate is found.

**Comment by prvak** [comment]
Thank you for the quick fix. I can confirm that the database loads with this change and the older one of the duplicate series is dropped.
