### ISSUE TITLE
Is there any data compression  method?

### ISSUE THREAD

**Issue by eleleme** [SiriDB/siridb-server#149]
Is there any data compression  method in SiriDB to compress IoTData， such as LZ4, Spinning Door Transformation?

**Comment by joente** [comment]
Hi @eleleme , for storing data on disk, SiriDB has build-in shard compression (must be enabled in the [configuration](https://github.com/SiriDB/siridb-server/blob/master/siridb.conf) file). 
There is currently no option within SiriDB to enable compression on the data which is being sent across the network.

**Comment by eleleme** [comment]
It does not matter to network transfer. What is the compresion ratios for different numeric type(i.e float, integer,double) ？As we know for timeseries data, LZ4 is often used to compress timestample and numberic value.

**Comment by joente** [comment]
The compression is created for SiriDB data only, and takes advantage of the fact that it knows about the data format which needs to be compressed and prefers speed over compression ratio but should still be able to reach a ratio between 4 and 5, even with floating point series. (integer series will most likely result in a higher compression ratio) 

*(On our monitoring platform we use only floating point series and have a compression ratio of almost 5.)*

**Comment by eleleme** [comment]
I have store about 500,000 records which come from a battery cell's voltage for one week, one point per scond. The database was created with nano-second precision. After insertion, the storage was about 5MB. As I know, one time series data point consists of one timestamp(8 bytes) and one float value(8bytes)，and all 500,000 records consume 500,000*16/1000000=8MB。 The compression ratio is not as big as 5.

**Comment by joente** [comment]
@eleleme , SiriDB creates larger files than required and then writes data into those files. There is also an index which is required to be written so SiriDB knows to which series a chunk of data belongs. Also, the compression ratio really depends on the data SiriDB is given, it is not guaranteed to give a ratio of 5. In our case we have second precision, and quite a lot of series with equal values over time and much more data (~210.000.000.000 records over ~2.3 million time series). 

It is also possible that SiriDB did not yet has optimized all shards, this usually takes some time.

Another option is to disable shard compression (start SiriDB with `SIRIDB_ENABLE_SHARD_COMPRESSION=0`). If you do, then SiriDB will de-compress all shards on the next optimization so this gives you the opportunity to compare the size with and without compression.
