### ISSUE TITLE
Question.  Time series model and query.

### ISSUE THREAD

**Issue by sptrakesh** [SiriDB/siridb-server#157]
Hello,

I am trying to find a replacement for our current Akumuli TSDB.  Akumuli (and Prometheus the other one I am familiar with) have the concept of tags (key-value pairs attached to series), which can be used to perform various types of analyses.  Looking at the documentation, I believe the equivalent with SiriDB is to create multiple series with the same timestamp and then query/merge them via regex query on series name.  Not totally clear from the documentation as to how that works in combination (coming from the perspective of using a tag values to filter series data).  Would appreciate some clarification on modelling data from those coming from other TSDBs.

Thanks
Rakesh

**Comment by bhasvij** [comment]
i am not seeing much response from this siriDb guys. Also noticed an issue in https://github.com/timescale/tsbs while generating data for siriDB for iot use case: https://github.com/timescale/tsbs/issues/179. Seems this is not yet matured to use in production currently

**Comment by joente** [comment]
SiriDB support a few different options to select series:
- **By name**, for example `select * from 'name1', 'name2'
- **By regular expression**, for example `select * from /name.*/
- **By group**, groups are regular expressions which are cached and thus fast to use, for example: ```select * from `group1` ```
- **By tag**, series can be tagged (of un-tagged), for example: ```select * from `tag1` ```

All the selectors above can be combined by using *set* operations between the selectors, for example: ```select * from `name1` | `name2` & `group2` - `tag1` ```

It is up to the user to use a naming convention for the series. An example structure might be `customer/asset/probe/metric` 

After selecting the series, `merge` can be used if you want a single serie per aggregation method as a result.
