### ISSUE TITLE
Possible memory corruption

### ISSUE THREAD

**Issue by ubnt-michals** [SiriDB/siridb-server#158]
First of all, I am not sure about this one. We have a couple of instances where SiriDB takes way more CPU and looks stuck (no points were inserted since it got into this state). The health-check is working ok :man_shrugging:.

Stack trace:
```
pcre2_match_8 0x00007f0f41d8f51c
async_series_re listener.c:5763
uv__async_io 0x00007f0f41de57b3
uv__io_poll 0x00007f0f41df343b
uv_run 0x00007f0f41de5d7a
siri_start siri.c:342
main main.c:76
libc_start_main_stage2 0x00007f0f41e1d1ef
_start 0x000055cdd1852e15
```

GDB says: `Program terminated with signal SIGSEGV, Segmentation fault.` I think that's not true because I took core dump from the running process and I think in the case of SIGSEGV it would be terminated.

The query is this one: `"select max() from /gateways\\.speed\\..*/ between now - 1d and now + 1h"`. I think escaping is not correct, but the query otherwise works and probably is not a culprit. That said I don't have a repro for this yet, but we are seeing this often so it's hopefully a matter of time.

I can provide the core dump if needed.

**Comment by ubnt-michals** [comment]
@joente I had some time to investigate the core dump a little bit more. It looks like some kind of memory corruption.

If you look at the iteration at: 

https://github.com/SiriDB/siridb-server/blob/0447d829851630a3bffcb5a00d2f48c59d15f753/src/siri/db/listener.c#L5758-L5776

The `series` struct looks like a garbage memory:

![image](https://user-images.githubusercontent.com/23234560/103318203-f76c8480-4a2d-11eb-8c88-460f5a13a63a.png)

The culprit, in this case, is `name_len` that (I think) makes no sense. Although the memory looks corrupted, it's properly allocated. The `pcre2_match` it's just slow going over a string that is 22kb long. Looks like all this is not synced to the disk because server restart helps for a couple of hours.

The core dump:
https://drive.google.com/file/d/1Vg91jwbN5DarMDfrMrOS-SF4pC6VSc6B/view?usp=sharing

**Comment by ubnt-michals** [comment]
@joente Could you please give me any pointers on where to start investigating? This is plaguing most of our instances. I can definitely allocate time to fix this, but I am not sure where to start looking for possible corruption.

We don't do anything fancy, 90% of our queries are inserts, the rest is `select mean()/min()/max()` with explicit series or regexp. There doesn't seem to be an easy repro case.

**Comment by joente** [comment]
@ubnt-michals, I'm not entirely sure where it goes wrong but I will look into this issue and hope to give you an answer soon. Do you know if the issue disappears once you eliminate regexp queries and stick to fixed or tagged series?

**Comment by ubnt-michals** [comment]
@joente @luznicky
Some more observations:

The corruption probably doesn't happen by deleting a series.

![image](https://user-images.githubusercontent.com/23234560/105201437-2bc0f580-5b41-11eb-8899-f2f11ea35e9e.png)

In this case `q_wrapper->vec->data[6000]` is the same pointer as `siridb->series_map->vec->data[6000]`. Deleting a series would cause the `siridb->series_map->vec` to be set to `NULL`. Also both `vec`s have the same `len`.

In this core dump, a total of 3 series indexed 5998, 5999, 6000 looks corrupt. The data in them are not totally random.

![image](https://user-images.githubusercontent.com/23234560/105202586-7000c580-5b42-11eb-86e7-90d5b3969f67.png)
![image](https://user-images.githubusercontent.com/23234560/105202617-78f19700-5b42-11eb-9fb2-72ab9f62486a.png)
![image](https://user-images.githubusercontent.com/23234560/105202674-8870e000-5b42-11eb-8a51-89287c7b507d.png)

For example, name_len is `22032` in all of them.

Also, the fact that they are allocated next to each other points me to some buffer overrun.

**Comment by ubnt-michals** [comment]
I think we have found a potential culprit of this memory corruption.

From the looks of it, the reference counting is not thread-safe.

The same locking that is for example here:

https://github.com/SiriDB/siridb-server/blob/ff989407c89aa214e2a0e90c6c9799b8f672e1ec/src/siri/db/shard.c#L1419-L1423

Is not here around `siridb_series_decref`
https://github.com/SiriDB/siridb-server/blob/ff989407c89aa214e2a0e90c6c9799b8f672e1ec/src/siri/db/shard.c#L1469

The "optimize" task runs in a different thread, and `siridb_series_incref` and `siridb_series_decref` are not atomic. Therefore they should create a race condition and use after `free` would explain what we see in the core dumps.

@joente can you confirm that that's the case? Maybe we are missing something and the use of `siridb_series_incref`/`siridb_series_decref` is not a problem.

**Comment by joente** [comment]
You are right, I missed this one.. Actually, I think replacing the `uint32_t ref` with `atomic_uint ref` should be enough to fix this issue since only one thread will decrement the ref count to zero. Do you have the option to try this fix?

**Comment by ubnt-michals** [comment]
I am testing https://github.com/SiriDB/siridb-server/pull/159 - basically the same thing. I'll let it run overnight.
