### ISSUE TITLE
HTTP Pipelining issue in embedded api service

### ISSUE THREAD

**Issue by srdgame** [SiriDB/siridb-server#161]
When I was testing query sql from one Firefox extension which called RESTer, the server is crashed on following code:

### src/siri/api.c

``` c
static int api__headers_complete_cb(http_parser * parser)
{
    siri_api_request_t * ar = parser->data;

    assert (!ar->buf);
```

The reason is that, that Firefox extension sending multiple HTTP requests via same socket connection.  Thus the headers_complete_cb called when server is executing message_complete_cb.

**Comment by joente** [comment]
@srdgame , I've created a pull request which should solve this issue, can you verify if #165 solves the issue?

**Comment by srdgame** [comment]
@joente Will test it ASAP, and provide you feedback then

**Comment by srdgame** [comment]
I have tested with your fixes, siridb-server will not be crashed in that test case.

By digging into query_cb, it is ok to free ar->buf as the ar->query will be copied inside siridb_query_run.  But I am not sure about other cases, e.g. insert post request from client?

**Comment by srdgame** [comment]
@joente The same issue when I am using Grafana siridb-http plugin with 9020 port.  After apply your patch, it seems that the query string does not been parsed correctly (at least the siri-server log does show the "Parsing query...."),  when typing series name in explore page of Grafana.  ( You have to input the series name quickly enough)

And by chance you will meet following issue, even you have correct series name

![image](https://user-images.githubusercontent.com/54447/106564821-b99cd780-6568-11eb-97db-a9a35e1f38cc.png)

![image](https://user-images.githubusercontent.com/54447/106564856-c7eaf380-6568-11eb-85dd-16091e0fe874.png)

**Comment by srdgame** [comment]
By having following changes, I have not meet the 'NOT FOUND' issue

![image](https://user-images.githubusercontent.com/54447/106565079-2a43f400-6569-11eb-96d9-0c12307f27d5.png)

**Comment by joente** [comment]
You're correct, I was a bit too fast with this solution, I'm thinking to keep a flag which can control for when the buffer requires a reset.

**Comment by joente** [comment]
@srdgame , I've updated the pull request

**Comment by srdgame** [comment]
@joente Will test it now

**Comment by srdgame** [comment]
@joente I have tested with my cases, it works.

And I am still worries about potential issue.  As we have following errors in log:

![image](https://user-images.githubusercontent.com/54447/106580216-9a0faa00-657c-11eb-9b1f-cb2b208b094b.png)


Could it better that having atomic lock to wait until the previous query been complete?

HTTP 1.1
```
8.1.2.2 Pipelining

A client that supports persistent connections MAY "pipeline" its requests (i.e., send multiple requests without waiting for each response). A server MUST send its responses to those requests in the same order that the requests were received.
```

**Comment by srdgame** [comment]
@joente 

About [HTTP pipelines ](https://en.wikipedia.org/wiki/HTTP_pipelining)

**Comment by srdgame** [comment]
this might helps [LINK](https://groups.google.com/g/libuv/c/i99lAqPpjTc/m/s7rlcMqfPRsJ)

**Comment by joente** [comment]
> 
> Could it better that having atomic lock to wait until the previous query been complete?
> 

A lock would not work since this would block the main thread. I think some change is required to keep track of the order in which requests are received since it is required to write responses back in the same order.

**Comment by srdgame** [comment]
@joente I have search for solution, it talks about parser pause.  And I have tried to make code changes and in my repo:

https://github.com/kooiot/siridb-server/commit/19fa5c1dae91f1cc19fdd7b1fbacfeb0b99066a4

**Comment by srdgame** [comment]
Currently, I do not know whether the uv_read_stop is an must or not.  It seems that parser pause is already fixes  my cases.

**Comment by joente** [comment]
> @joente I have search for solution, it talks about parser pause. And I have tried to make code changes and in my repo:
> 
> [kooiot@19fa5c1](https://github.com/kooiot/siridb-server/commit/19fa5c1dae91f1cc19fdd7b1fbacfeb0b99066a4)

:+1:

**Comment by srdgame** [comment]
Will make more testing today.

**Comment by srdgame** [comment]
@joente All my tests are passed with the fixes
