### ISSUE TITLE
Confused about database duration and shards expiration

### ISSUE THREAD

**Issue by srdgame** [SiriDB/siridb-server#162]
e.g I created the database with 4 weeks duration, and then set the expiration_num to 0.  Does it means that the data will never been dropped? or will be dropped when reach database's duration?

BTW: why the duration cannot be bigger than 99w? is this limited by design?

**Comment by joente** [comment]
@srdgame, the shard duration is the time span of data which is stored in a *single* shard. 

For example: you might have data for some year with a shard duration of 1 week, then SiriDB will use 52 shards to store this data. 

When having an expiration time set, the shards which are older will be dropped automatically. 

A SiriDB shard duration of about 1 week is fine for series with a sample rate of about a minute. Some higher value might be used if your series have a much lower sample rate, for example once in a few hours, and a lower duration for series with a second sample rate. SiriDB can choose a shard duration for time series automatically series when you have auto shard duration enabled (`enable_shard_auto_duration`).

**Comment by srdgame** [comment]
@joente Thanks very much for your information.   

And if it is possible that the duration of database been set much longer than 99 weeks? e.g. 10 years?

what is that reason that limited the duration by this way?

``` c
    val = strtol((const char *) qp_duration->via.raw, &endptr, 10);

    if (val < 1 || val > 99 || endptr == (const char *) qp_duration->via.raw)
    {
        return -1;
    }
```

**Comment by joente** [comment]
> @joente Thanks very much for your information.
> 
> And if it is possible that the duration of database been set much longer than 99 weeks? e.g. 10 years?
> 
> what is that reason that limited the duration by this way?
> 
> ```c
>     val = strtol((const char *) qp_duration->via.raw, &endptr, 10);
> 
>     if (val < 1 || val > 99 || endptr == (const char *) qp_duration->via.raw)
>     {
>         return -1;
>     }
> ```

The value is a bit arbitrary but 99 weeks is just a very, very long duration for a single shard. It is no problem to have data for more than 10 years, but why should you want SiriDB to use a single shard instead of using multiple shards for such a time period?

**Comment by srdgame** [comment]
@joente Sorry, I had an misunderstanding about duration and expiration.
