### ISSUE TITLE
Is there any detailed document for setup pool(s)?

### ISSUE THREAD

**Issue by eleleme** [SiriDB/siridb-server#166]
Is there any detailed document for setup pool(s) step by step?

**Comment by joente** [comment]
@eleleme, The basic idea is to create a database on the first server and create pools on the other servers.

To do this, you can use [siridb admin](https://github.com/SiriDB/siridb-admin) which uses the siridb socket connection (default port 9000) and provides a graphical user interface. It is also possible to use plain [HTTP API](https://docs.siridb.net/connect/http_api/) requests if you have this enabled on your siridb servers.

For example, we could use the HTTP API and create the following using curl requests:

- A database *sampledb* with *second* time precision.
- Three pools:
  - Pool 0: running on host: "siridb0"
  - Pool 1: running on host: "siridb1"
  - Pool 2: running on host: "siridb2"
- Assume that the accounts are left to the default (service account *sa* with password *siri* and database user *iris* with password *siri*).
- Assume that the siridb hosts are listening to 9000 for client connections *(this is default)* and 9020 for HTTP API request *([SIRIDB_HTTP_API_PORT](https://docs.siridb.net/getting_started/configuration/) must be set to 9020)*. 


Create the database on host *siridb0*

```
curl --location --request POST 'http://siridb0:9020/new-database' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic c2E6c2lyaQ==' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"dbname": "sampledb",
	"time_precision": "s",
}'
```

Create another pool on host *siridb1*

```
curl --location --request POST 'http://siridb1:9020/new-pool' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic c2E6c2lyaQ==' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"dbname": "sampledb",
	"username": "iris",
	"password": "siri",
	"host": "siridb0",
    "port": 9000
}'
```

And yet another pool on host *siridb2*

```
curl --location --request POST 'http://siridb2:9020/new-pool' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic c2E6c2lyaQ==' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"dbname": "sampledb",
	"username": "iris",
	"password": "siri",
	"host": "siridb0",
	"port": 9000
}'
```

**Comment by kimboox44** [comment]
What about replica in same host, documentation mention single pool may have 2 servers (replica) how to set that ?

**Comment by joente** [comment]
@kimboox44 , hope this will answer your question:

Suppose you want to run two servers in *pool 0*, and host *siridb0* is the first server hosting *pool 0*, we could add a replica on host *siridb1* with the following command:

```bash
curl --location --request POST 'http://siridb1:9020/new-replica' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic c2E6c2lyaQ==' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"dbname": "sampledb",
        "username": "iris",
        "password": "siri",
        "host": "siridb0",
        "port": 9000,
        "pool": 0
}'
```

If you want a second server on the *same* host, then the *second* server must use different ports. For example:

```ini
SIRIDB_SERVER_NAME = %HOSTNAME:9011
SIRIDB_LISTEN_CLIENT_PORT = 9001
SIRIDB_HTTP_API_PORT = 9021
```

**Comment by kimboox44** [comment]
Did exactly that (same host) in admin
logged to server0 -> create database -> "rts_siri"
logged to server0 ->databases->db0->new pool give error "database name already exists: 'rts_siri'"
logged to server1-> databases->new replica-> same error "database name already exists: 'rts_siri'"
changed folder path of server1 same
logged to server1-> databases->new replica-> same error "database name already exists: 'rts_siri'"
logged to server1-> databases->new pool-> same error "database name already exists: 'rts_siri'"
logged to server0-> databases->new pool-> same error "database name already exists: 'rts_siri'"
