### ISSUE TITLE
Simple insert

### ISSUE THREAD

**Issue by ovresko** [SiriDB/siridb-server#174]
Hi i can't find how to send a simple insert cmd (no clients) , docs talk about all high levels stuff but a simple insert query is nowhere to be found.
can we do multi value insert, array like value? is so how to format the data
because trying to do multi insert with python 
```
for a in range(500):
            await siri.insert({'send1': [[ts,value]],'sens2': [[ts,value]],'sens3': [[ts, value]],'sens4': [[ts, value]],'sens5': [[ts, 343*value]]})
```
this toke   23.13 sec to execute, i suspected that something is wrong, i can run same write to mariadb in 0.53 sec

**Comment by joente** [comment]
Hi @ovresko ,You probably have some serious error, the code above took only 0.044 sec on my laptop (~10 times faster than your write to mariadb). I honestly have no idea how it could take more than 23 sec but you might want to try to set `SIRIDB_BUFFER_SYNC_INTERVAL` to something like 500. See https://docs.siridb.net/getting_started/configuration/.

SiriDB only supports `int`, `float` and `string` values, no multi-dimensional data. You can however, build multiple timestamp/values in a single request. For example:

```python
await siri.insert({'send1': [[ts1,value1], [ts2,value2], [ts3,value3]...]})
```

If you want to use something else than Python, you might want to look at the http api: https://docs.siridb.net/connect/http_api/#insert-request

**Comment by ovresko** [comment]
Thank you, i did manage to make it work, 
for data types SiriDB only supports int, float and string values, what can i do to prevent duplicates/overlap of records with same ts and series, somehing like retention policy (first, last, error), it's likea standard for any TSDB.

**Comment by ovresko** [comment]
I did find where select_points_limit is used, that's the closest thing to a limit defined by client query but  it reads it from config
on_select_response function
https://github.com/SiriDB/siridb-server/blob/23664bdb08b690022d0fdd6a4a8336592e0a7529/src/siri/db/listener.c#L6864

**Comment by joente** [comment]
SiriDB had support for a limit, much like the one you want: https://docs.siridb.net/query_data/aggregate_functions/limit/ 
In the code, this is not the `select_points_limit` as that is general limit to protect SiriDB from making insane large queries. The *limit* you want is defined in `aggregate.c` (AGGREGATE_limit).
