### ISSUE TITLE
Disk Failure

### ISSUE THREAD

**Issue by uzunenes** [SiriDB/siridb-server#181]
Hello,

We have an IoT SiriDB database that has 2 servers and 4 pools. Disk of Server1-Pool0 crashed and lost all data yesterday. Database is working stable using Pool0-Server2.

![image](https://user-images.githubusercontent.com/42443500/184618374-b02d315a-3ae0-4459-914c-813508d705f1.png)

We chanced the failure disk to new disk on Server1. How can we readjust cluster structure on Database and sync two servers-pools?

Best Regards,
Enes

**Comment by riklempens** [comment]
The first step is ensure you have proper backups, see our backup documentation [here](https://docs.siridb.com/servers/alter_server/backup_mode/)

The steps to remediate your issue are:

1. Drop the "broken" server as outlined [here](https://docs.siridb.com/servers/drop_servers/)
2. Create a [new replica](https://github.com/SiriDB/siridb-admin#new-replica)

The new node will have the 'running | synchronizing' status while the replica is being rebuild, when the replica is finished the status should be 'running'.

Depending on the size of your cluster this can take quite some time.

**Comment by riklempens** [comment]
Closing this issue, please reopen if there are further questions regarding this issue.
