### ISSUE TITLE
Support for rate aggregation

### ISSUE THREAD

**Issue by ImapUkua** [SiriDB/siridb-server#189]
I am evaluating SiriDB as a store for SNMP metrics. Common series in this model are the interface packet counters indicating the number of packets sent and received by an interface. These are logged as a timestamp with a simple 64bit integer. 

In order to get the data rate (packets per second) for an interface, I would need the difference between the packet counters, divided by the collection interval (in seconds). 

Using the following query, I get 2 series as a response which would have to be processed further at the application level:
`select difference() suffix "_delta", interval() suffix "_interval" from 'snmp_interface_1' after now - 1h`

Does SiriDB support dividing the delta by the interval in the returning series in any way? 

If that is not the case, would you consider adding support for basic mathematical operations between resulting (numerical) series? 
I was thinking about addition, subtraction, multiplication and division with possibly exponentiation, modulus calculation and prioritization using brackets. 

For my case using a database with millisecond precision, an example syntax might be:
`select difference() / interval() * 1e3 from 'snmp_interface_1' after now - 1h`

**Comment by joente** [comment]
Hi @ImapUkua , the `derivative(1s)` aggregation method is most likely what you need?

See: https://docs.siridb.com/query_data/aggregate_functions/derivative/

**Comment by ImapUkua** [comment]
Completely missed that one, thank you for the the hint!

**Comment by riklempens** [comment]
@ImapUkua as you show an interested in SNMP I assume your in the area of IT infrastructure monitoring, as such you might be interested in [InfraSonar](https://infrasonar.com).

InfraSonar is open source and offers a managed platform for handling monitoring data.
InfraSonar is also developed by us, full disclosure we developed SiriDB for this platform so you use case is spot-on.

Even if you are not interested in InfraSonar we would appreciate it if you could spread a kind word about SiriDB, that is if you like it or even considering sponsoring our project if you really like it.
