### ISSUE TITLE
Native client for Java

### ISSUE THREAD

**Issue by michalperlak** [SiriDB/siridb-server#63]
Are you planning development of native client for Java?

**Comment by joente** [comment]
Yes, we do have plans for writing native clients for C/C++ and Java. I'll keep this issue open until the native client for Java is finished. It will probably take a few weeks so for the time being you (maybe) can use the [HTTP connector](https://github.com/transceptor-technology/siridb-http)?

**Comment by michalperlak** [comment]
Thank you for your response. I will try the HTTP connector.

**Comment by unicolet** [comment]
@joente we would like to have native client for Java :-) Is there a protocol spec somewhere that we can look at? I looked at python, but I'd avoid reverse-engineering the code, is possible :wink:

**Comment by unicolet** [comment]
just found https://github.com/SiriDB/java-siridb-connector

I guess we'll just have to be patient :-)

**Comment by joente** [comment]
We now have a native Java Connector for SiriDB available: https://github.com/SiriDB/java-siridb-connector/releases/latest

**Comment by unicolet** [comment]
thanks @joente !
